#!/bin/env python3.11
import argparse
import datetime
import io
import pathlib

from questdb_connect import Symbol, PartitionBy, Double, Timestamp, QDBTableEngine
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.types import DateTime, String, Float
import h5py
import hdf5plugin
import numpy as np
import numpy.typing as npt
from rich.progress import track
import sqlalchemy

PRICE_PRECISION = 0.01
TIMESTAMP_PRECISION = 60 # In seconds

class Base(sqlalchemy.orm.DeclarativeBase):
    pass

class Tick(Base):
    __tablename__ = 'prices'
    __table_args__ = (QDBTableEngine(None, 'timestamp', PartitionBy.HOUR, is_wal=True),)

    symbol: Mapped[str] = mapped_column(Symbol)
    open: Mapped[float] = mapped_column(Double)
    high: Mapped[float] = mapped_column(Double)
    low: Mapped[float] = mapped_column(Double)
    close: Mapped[float] = mapped_column(Double)
    timestamp: Mapped[datetime.datetime] = mapped_column(Timestamp, primary_key=True)

    def __repr__(self) -> str:
        return (
            f'<Tick {self.symbol} @ {self.timestamp} open={self.open} high={self.high} '
            f'low={self.low} close={self.close}>')

    def array(self) -> list[int]:
        timestamp = int(self.timestamp.timestamp() / TIMESTAMP_PRECISION)
        open_ = int(self.open / PRICE_PRECISION)
        high = int(self.high / PRICE_PRECISION)
        low = int(self.low / PRICE_PRECISION)
        close = int(self.close / PRICE_PRECISION)
        return [timestamp, open_, high, low, close]

class SystemEvent(Base):
    __tablename__ = 'system_events'

    type: Mapped[str] = mapped_column(Symbol)
    timestamp: Mapped[datetime.datetime] = mapped_column(Timestamp, primary_key=True)

    def __repr__(self) -> str:
        return f'<SystemEvent {self.type} @ {self.timestamp}>'

    def __int__(self) -> int:
        match self.type:
            case 'system_hours_start':
                return 0
            case 'regular_hours_start':
                return 1
            case 'regular_hours_end':
                return 2
            case 'system_hours_end':
                return 3
            case _:
                raise UnknownSystemEventError(self.type)

    def array(self) -> list[int]:
        timestamp = int(self.timestamp.timestamp() / TIMESTAMP_PRECISION)
        type_ = int(self)
        return [timestamp, type_]

class UnknownSystemEventError(Exception):
    """Raised when an unknown system event type is encountered."""
    def __init__(self, event_type: str):
        self.event_type = event_type
        super().__init__(f'Unknown system event type: "{event_type}"')

def download_prices(db_session: sqlalchemy.orm.Session, output_group: h5py.Group) -> None:
    symbols = db_session.scalars(sqlalchemy.select(sqlalchemy.distinct(Tick.symbol))).all()

    prices_group = output_group.create_group('prices')

    for symbol in track(symbols, description='Downloading prices'):
        assert '/' not in symbol
    
        count = db_session.scalar(
            sqlalchemy.select(sqlalchemy.func.count())
            .select_from(Tick)
            .where(Tick.symbol == symbol))

        # TODO Maybe Blosc2 works with Rust?
        ds = prices_group.create_dataset(
            symbol,
            (count, 5),
            chunks=True,
            dtype=np.int32,
            compression=hdf5plugin.Blosc())

        ticks = db_session.scalars(sqlalchemy.select(Tick).where(Tick.symbol == symbol))
        for i, tick in enumerate(ticks):
            ds[i] = tick.array()

def download_system_events(db_session: sqlalchemy.orm.Session, output_group: h5py.Group) -> None:
    count = db_session.scalar(
        sqlalchemy.select(sqlalchemy.func.count())
        .select_from(SystemEvent))

    ds = output_group.create_dataset(
        'system_events',
        (count, 2),
        chunks=True,
        dtype=np.int32,
        compression=hdf5plugin.Blosc())

    system_events = db_session.scalars(sqlalchemy.select(SystemEvent))
    for i, event in enumerate(track(system_events, description='Downloading system events')):
        ds[i] = event.array()
    
def download_to_hdf5(
        db_url: pathlib.Path,
        output_file: io.RawIOBase,
        extend: bool = False,
        prices: bool = True,
        system_events: bool = True) -> None:
    db_engine = sqlalchemy.create_engine(db_url)
    
    write_mode = 'r+' if extend else 'w'
    with h5py.File(output_file, write_mode) as f, sqlalchemy.orm.Session(db_engine) as db_session:
        if prices:
            download_prices(db_session, f)
        if system_events:
            download_system_events(db_session, f)

def mmatamm_qdb2hdf5():
    argparser = argparse.ArgumentParser(
        description='Download financial data generated by mmatamm-fetch from QuestDB to HDF5')
    argparser.add_argument('file', type=pathlib.Path, help='The HDF5 file to write to')
    argparser.add_argument(
        '--db-user',
        type=str,
        default='admin',
        help='The database username to use')
    argparser.add_argument(
        '--db-password',
        type=str,
        default='quest',
        help='The password for the database user')
    argparser.add_argument('--db-host', type=str, default='localhost', help='The database host')
    argparser.add_argument('--db-port', type=int, default=8812, help='The database TCP port')
    argparser.add_argument(
        '--db-database',
        type=str,
        default='qdb',
        help='The name of the database to use')
    argparser.add_argument(
        '-e', '--extend',
        action='store_true',
        help='Add to the output file instead of overwriting it if it exists')
    argparser.add_argument(
        '--skip-prices',
        action='store_true',
        help='Don\'t download price data')
    argparser.add_argument(
        '--skip-system-events',
        action='store_true',
        help='Don\'t download system events data')
    args = argparser.parse_args()

    db_url = sqlalchemy.URL.create(
        'questdb',
        username=args.db_user,
        password=args.db_password, 
        host=args.db_host,
        port=args.db_port,
        database=args.db_database)

    download_to_hdf5(
        db_url,
        args.file,
        args.extend,
        not args.skip_prices,
        not args.skip_system_events)
    

if __name__ == '__main__':
    mmatamm_qdb2hdf5()
